# Generated by Django 5.2.6 on 2026-02-11 19:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tunnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tunnel_id",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tunnel ID must be 4-32 chars, lowercase letters/digits/hyphen, and cannot start/end with hyphen.",
                                regex="^[a-z0-9](?:[a-z0-9-]{2,30}[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                ("connect_key_hash", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=False)),
                ("local_target_url", models.URLField(blank=True, default="")),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TunnelRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("method", models.CharField(max_length=16)),
                ("path", models.TextField()),
                ("query_string", models.TextField(blank=True, default="")),
                ("request_headers", models.JSONField(default=dict)),
                ("request_body_b64", models.TextField(blank=True, default="")),
                ("request_body_size", models.PositiveIntegerField(default=0)),
                ("request_body_binary", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("leased", "Leased"),
                            ("responded", "Responded"),
                            ("timed_out", "Timed out"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("leased_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response_status", models.PositiveIntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(default=dict)),
                ("response_body_b64", models.TextField(blank=True, default="")),
                ("response_body_size", models.PositiveIntegerField(default=0)),
                ("response_body_binary", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "tunnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="tunnel.tunnel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
