# Generated by Django 5.2.6 on 2026-02-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunnel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tunnel",
            name="ws_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tunnel",
            name="ws_connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tunnel",
            name="ws_connection_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
