# Generated by Django 5.2.6 on 2026-02-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunnel", "0002_tunnel_ws_connected_tunnel_ws_connected_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tunnel",
            index=models.Index(
                fields=["is_active", "last_seen"], name="tunnel_active_seen_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tunnelrequest",
            index=models.Index(
                fields=["tunnel", "status", "created_at"], name="tunnel_req_queue_idx"
            ),
        ),
    ]
