# Generated by Codex on 2026-02-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tunnel", "0003_tunnel_tunnel_active_seen_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tunnel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tunnels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="tunnel",
            index=models.Index(fields=["owner", "created_at"], name="tunnel_owner_created_idx"),
        ),
    ]
