# Generated by Codex on 2026-02-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tunnel", "0004_tunnel_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("base_url", models.URLField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("variables", models.JSONField(blank=True, default=list)),
                ("auth", models.JSONField(blank=True, default=dict)),
                ("scripts", models.JSONField(blank=True, default=dict)),
                ("created_at_ms", models.BigIntegerField(default=0)),
                ("updated_at_ms", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "updated_at"], name="api_coll_owner_updated_idx"),
                    models.Index(fields=["owner", "created_at"], name="api_coll_owner_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("owner", "client_id"), name="api_collection_owner_client_uidx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ApiSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("version", models.CharField(blank=True, default="", max_length=32)),
                ("source", models.TextField(blank=True, default="")),
                ("request_schema", models.JSONField(blank=True, default=dict)),
                ("response_schema", models.JSONField(blank=True, default=dict)),
                ("created_at_ms", models.BigIntegerField(default=0)),
                ("updated_at_ms", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "updated_at"], name="api_schema_owner_updated_idx"),
                    models.Index(fields=["owner", "created_at"], name="api_schema_owner_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("owner", "client_id"), name="api_schema_owner_client_uidx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ApiCollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=64)),
                ("parent_client_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("folder", "Folder"), ("request", "Request")],
                        db_index=True,
                        default="request",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                ("url", models.TextField(blank=True, default="")),
                ("headers", models.JSONField(blank=True, default=list)),
                ("params", models.JSONField(blank=True, default=list)),
                ("body", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at_ms", models.BigIntegerField(default=0)),
                ("updated_at_ms", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tunnel.apicollection",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "indexes": [
                    models.Index(fields=["collection", "parent_client_id", "sort_order"], name="api_item_tree_idx"),
                    models.Index(fields=["collection", "item_type"], name="api_item_type_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("collection", "client_id"), name="api_coll_item_collection_client_uidx")
                ],
            },
        ),
    ]
